# This is a basic workflow to help you get started with Actions

name: example_workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ react_app_deploy ]

jobs:
  
  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run install
        run: npm install 
      - name: Run build 
	run: npm run build
      - uses: actions/upload-artifact@v2
        with: 
          name: my-artifact
	  path: path/to/artifact/world.txt  
  deploy:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/download-artifact@v2
      - uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'highfalutin-sisters.surge.sh'
          project: '.'
          login: 'juan.antonio.lis@gmail.com'
          token: 'b9124d4f0d06d49b40471491b89e9ef0'
      
        
        
